### ISSUE TITLE
embed_install_prefix produces empty files when a custom install prefix is used

### ISSUE THREAD

**Issue by haellowyyn** [paylogic/py2deb#9] opened 2017-01-10 18:22 UTC
I noticed that, when using a custom install prefix, the .deb packages generated by py2deb contain empty files in the `<install-prefix>/bin/` folder. For example, when using py2deb to build a uwsgi package, the `uwsgi` binary is an empty file in the resulting package.

I tracked this error to `py2deb.package.PackageToConvert.transform_binary_dist`. If a custom install prefix is used, this function calls `py2deb.utils.embed_install_prefix` on files in the `bin/` folder. `embed_install_prefix` inspects the contents of these files to find out if they are Python executables and, if so, injects some code into them. The problem occurs only for files that are not Python executables (i.e. they lack the respective shebang). The contents of those files are read from the `handle` parameter, then the function immediately returns. As `handle` is a file-like object, this reading of the contents advances the file pointer to the end of the file. Later, `handle` is read again to copy the file to its final destination in the .deb package, but as the file pointer is still at EOF, the resulting file is empty.

To fix this, we could simply reset the file pointer of `handle` at the end of `embed_install_prefix`.

**Comment by xolox** [comment] 2017-01-17 01:12
Hi Jan and thanks for the feedback! To be honest I never consciously realized that Python packages can install binary executables, because I'd never encountered any in the packages that I've worked with over the years. I added [a test that reproduces the issue](https://travis-ci.org/paylogic/py2deb/builds/192538571) you reported and then merged your pull request, which [fixed the test](https://travis-ci.org/paylogic/py2deb/builds/192538964) (as expected). The bug fix is available in py2deb version 0.24.4 which I just released to PyPI and GitHub.

**Closed by xolox** 2017-01-17 01:12 UTC
